Repository tvaroglu/spot_me_backend, pull requests merged in 2021-09, with the labels that each got.

#50 Enum branch
  Gemfile.lock
  app/models/user.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
  spec/requests/api/v1/users/create_request_spec.rb
  spec/requests/api/v1/users/find/index_request_spec.rb
  spec/serializers/user_serializer_spec.rb
Labels: bug

#52 4 documentation
  README.md
  docs/friendships.md
  docs/gym_memberships.md
  docs/gyms.md
  docs/users.md
Labels: documentation

#54 5 get gym member users endpoint
  app/controllers/api/v1/gym_memberships/users_controller.rb
  config/routes.rb
  spec/requests/api/v1/gym_memberships/users/index_request_spec.rb
Labels: Endpoint

#56 Fix bug in users/events create
  app/controllers/api/v1/users/gym_memberships/events_controller.rb
  spec/requests/api/v1/users/gym_memberships/events/create_request_spec.rb
Labels: Endpoint

#58 Improve README
  README.md
Labels: documentation
